export const p5Works = [
  {
    number: "01",
    slug: "wonderful-moonstone",
    title: "WONDERFUL MOONSTONE",
    label: "INTERACTIVE DRAWING",
    date: "2026.09.13",
    description: "以游標作為畫筆，讓不同尺寸與色彩的圓形在黑色畫布上持續疊加。",
    instruction: "MOVE THE POINTER TO DRAW",
    src: "/p5js/wonderful-moonstone/index.html",
  },
  {
    number: "02",
    slug: "zenith-marlin",
    title: "ZENITH MARLIN",
    label: "GENERATIVE MOTION",
    date: "2026.09.16",
    description: "由正弦波驅動的點陣系統，透過位置與尺寸變化形成連續流動的視覺節奏。",
    instruction: "GENERATIVE LOOP",
    src: "/p5js/zenith-marlin/index.html",
  },
  {
    number: "03",
    slug: "senbonzakura",
    title: "SENBONZAKURA",
    label: "GENERATIVE ANIMATION",
    date: "2026.09.19",
    description: "刀刃逐步解構為櫻花碎片，在循環動畫中呈現聚合、消散與重生。",
    instruction: "CLICK TO TRIGGER THE TRANSFORMATION",
    src: "/p5js/senbonzakura/index.html",
  },
  {
    number: "04",
    slug: "bronze-marquess",
    title: "BRONZE MARQUESS",
    label: "INTERACTIVE 3D",
    date: "2026.09.19",
    description: "以游標控制一天中的時間，讓 3D 玫瑰隨日照改變光線、天空與花瓣開合。",
    instruction: "MOVE HORIZONTALLY TO CHANGE TIME",
    src: "/p5js/bronze-marquess/index.html",
  },
  {
    number: "05",
    slug: "first",
    title: "FIRST",
    label: "GENERATIVE COMPOSITION",
    date: "2026.09.19",
    description: "將油彩色塊、裂紋、玻璃碎片與塵埃隨機組合為每次都不同的抽象畫面。",
    instruction: "CLICK TO REGENERATE THE COMPOSITION",
    src: "/p5js/first/index.html",
  },
  {
    number: "06",
    slug: "pyramid",
    title: "PYRAMID",
    label: "GENERATIVE LIGHT",
    date: "2026.09.19",
    description: "以方格堆疊出階梯式金字塔，讓環繞光源持續改寫表面的明暗與陰影。",
    instruction: "GENERATIVE LIGHT LOOP",
    src: "/p5js/pyramid/index.html",
  },
];

export function getP5Work(slug) {
  return p5Works.find((work) => work.slug === slug);
}
